### ISSUE TITLE
Update all report name references to: Technical Phishing Test (TPT)

### ISSUE THREAD

**Issue by schmelz21** [cisagov/tpt-reports#29]
# 💡 Summary #

Leadership has determined that it is best to rebrand the service as Technical Phishing Test (TPT). All code references and documentation should be updated.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Reports run with no references to Technical Payload Testing (TPT)
- [ ] Code doctrings are updated
- [ ] GitHub description and READ.ME has been updated.
